# Plik MiniBank/pytest.ini konfiguruje zachowanie pytest dla testów asynchronicznych.
# asyncio_mode = auto
#                 włącza automatyczną obsługę testów asynchronicznych (np. async def),
#                                       tak że plugin`pytest-asyncio` uruchomi je w pętli zdarzeń.
# asyncio_default_fixture_loop_scope = function
#                 ustawia domyślny zakres fixture`a event loop na function,
#                                       czyli tworzy nową pętlę zdarzeń dla każdego testu (izolacja między testami).


[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function