services:
  api:
    build: .
    container_name: minibank_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app # Montujemy kod lokalny do kontenera, żeby działał hot-reload!
    environment:
      - DATABASE_URL=postgresql+asyncpg://bank_admin:superhaslo123@db:5432/minibank
      - PYTHONPATH=/app
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: minibank_db
    restart: always
    ports:
      - "5433:5432"  # Mapowanie 5433:5432 oznacza: port hosta : port kontenera.
    environment:
      POSTGRES_USER: bank_admin
      POSTGRES_PASSWORD: superhaslo123
      POSTGRES_DB: minibank
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: