# Plik MiniBank/pytest.ini konfiguruje zachowanie pytest dla testów w projekcie, głównie obsługę testów asynchronicznych:
# uzycie
# asyncio_mode = auto — włącza/pozwala na automatyczne użycie obsługi asyncio przez plugin (pytest-asyncio),
# dzięki czemu testy async def są prawidłowo uruchamiane.

# asyncio_default_fixture_loop_scope = function — ustawia zakres (scope) domyślnej pętli zdarzeń na poziom funkcji,
# czyli każdemu testowi przydzielana jest świeża pętla (izolacja między testami).

# Pytest odczytuje ten plik automatycznie przy uruchamianiu testów.



[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function